service:
  name: employeescrud

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:*

functions:
  createEmployee:
    handler: src/functions/createEmployee.handle
    events:
      - http:
          path: /createEmployee
          method: POST
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
        - dynamodb:PutItem
    Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/employees"
  getAllEmployees:
    handler: src/functions/getAllEmployees.handle
    events:
      - http:
          path: /getAllEmployees
          method: GET
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
    Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/employees"
  getAllEmployeeById:
    handler: src/functions/getEmployeeById.handle
    events:
      - http:
          path: /getEmployeeById/{id}
          method: GET
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
    Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/employees"
  updateEmployee:
    handler: src/functions/updateEmployee.handle
    events:
      - http:
          path: /updateEmployee/{id}
          method: PUT
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
        - dynamodb:UpdateItem
    Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/employees"
  deleteEmployee:
    handler: src/functions/deleteEmployee.handle
    events:
      - http:
          path: /deleteEmployee/{id}
          method: DELETE
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
        - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/employees"

resources:
  Resources:
    dbEmployees:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH